name: "Release devcontainer image"
on:
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build and publish dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/schamper/dissect-devcontainer
          push: always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
