name: "Release devcontainer image"
on:
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Release devcontainer (${{ matrix.arch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: linux/amd64
          - arch: linux/arm64
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx for multi-architecture builds
        if: ${{ matrix.arch }} == 'linux/arm64'
        uses: docker/setup-buildx-action@v3
        with:
          use: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build and publish dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/schamper/dissect-devcontainer
          cacheFrom: ghcr.io/schamper/dissect-devcontainer
          platform: ${{ matrix.arch }}
          push: filter
          refFilterForPush: refs/heads/main
          eventFilterForPush: |
            workflow_dispatch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
